<?php
$title = 'Change Password';
$display_status = $this->UtilHelper()->displayStatus();
$hidden_items = $this->UtilHelper()->hiddenElements();
?>
<script type="text/javascript">
    /* <![CDATA[ */
    jQuery(function () {
        jQuery("#password").validate({
            expression: "if (VAL.length > 5 && VAL) return true; else return false;",
            message: "Password should be minimum 6 charanters."
        });
        jQuery("#repassword").validate({
            expression: "if (VAL.length > 5 && VAL) return true; else return false;",
            message: "Confirm password should be minimum 6 charanters."
        });
        jQuery("#repassword").validate({
            expression: "if ((VAL == jQuery('#password').val()) && VAL) return true; else return false;",
            message: "Confirm password doesn't match with password."
        });
        occ.passwordStrengthChecker();
    });
    /* ]]> */
</script>
<div class="occ-container">
    <div class="row">
        <?php // echo $this->partial('zf2auth/elements/message.phtml', array ('flashMessages' => $this->flashMessages, 'error' => $this->error)); ?>
        <?php echo $this->partial('partial/message.phtml', array('flashMessages' => $this->flashMessages, 'error' => $this->error)); ?>
        <div class="panel">
            <div class="panel-heading">
                <?php echo $this->escapeHtml($title); ?>
            </div>
            <div class="panel-body">
                <?php
                $successMessage = "";
                foreach ($this->flashMessages as $mess) {
                    $successMessage = $mess["success"];
                }
                if (empty($successMessage) && is_object($this->form)) {

                    $form = $this->form;
                    $form->setAttribute('action', $this->url('users/change-password'));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    foreach ($form as $element) :
                        if (empty($display_status)) {
                            $name = $element->getName();
                            if (in_array($name, $hidden_items)) {
                                continue;
                            }
                        }
                        $current_class = $element->getAttribute('class');
                        $class_array = explode(' ', $current_class);
                        $current_type = $element->getAttribute('type');
                        ?>
                        <div class="form-group <?php echo ($current_type == 'hidden') ? $current_type : ''; ?>">
                            <label class="col-sm-8 control-label"><?php echo $element->getLabel(); ?></label>
                            <div class="col-sm-16">
                                <?php
                                if ($this->formElementErrors($element)) {
                                    $element->setAttribute('class', $current_class . ' ErrorField');
                                }
                                echo $this->formElement($element);
                                if ($this->formElementErrors($element)):
                                    ?>
                                    <span class="ValidationErrors"><?php echo $this->formElementErrors($element); ?></span>
                                    <?php
                                endif;
                                ?>
                            </div>
                        </div>
                        <?php
                    endforeach;
                    ?>
                    <div class="form-group">
                        <div class="col-sm-16  col-sm-push-8">
                            <button class="btn btn-primary" type="submit">Submit</button>
                            <button class="btn btn-default reset" type="reset" onclick="history.back();">Cancel</button>
                        </div>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>

                    <?php
                }else {
                    
                }
                /*
                  $successMessage = "";
                  foreach ($this->flashMessages as $mess) {
                  $successMessage = $mess["success"];
                  }
                  if (empty($successMessage) && is_object($this->form)) {

                  $form    = $this->form;
                  $form->setAttribute('action', $this->url('users/change-password'));
                  $form->setAttribute('id', 'changePasswordForm');
                  $form->prepare();
                  echo $this->form()->openTag($form);
                  $allname = array ();
                  foreach ($form as $element) :
                  $name      = $element->getAttribute('id');
                  $allname[] = $name;
                  $$name     = $element;
                  endforeach;


                  foreach ($form as $element) :

                  echo $this->formElement($element);
                  if ($this->formElementErrors($element)):
                  ?>
                  <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                  <?php
                  endif;

                  endforeach;
                  }else {

                  }
                 *
                 */
                ?>
            </div>
        </div>
    </div>
</div>