<?php
$title = 'Forgot password?';
?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('users/forgot-password'));
$form->setAttribute('class', 'form-signin');
$form->prepare();
echo $this->form()->openTag($form);
$allname = array();
foreach ($form as $element) :
    $name = $element->getAttribute('id');
    $allname[] = $name;
    $$name = $element;
endforeach;
?>
<h2 class="form-signin-heading"><?php echo $this->escapeHtml($title); ?></h2>
<div class="login-wrap">
    <div class="user-login-info">

        <?php echo $this->partial('zf2auth/elements/message.phtml', array('flashMessages' => $this->flashMessages, 'error' => $this->error)); ?>

        <?php
// Email
        if ($this->formElementErrors($email)) {
            $class = '';
            $class = $email->getAttribute('class');
            $class = $class . ' ErrorField';
            $email->setAttribute('class', $class);
        }
        ?>
        <div class=" <?php if ($this->formElementErrors($email)) echo "error"; ?>">
            <?php
            echo $this->formElement($email);
            if ($this->formElementErrors($email)):
                ?>
                <span class="help-inline"><?php echo $this->formElementErrors($email); ?></span>
                <?php
            endif;
            ?>
        </div>
    </div>

    <?php
    echo $this->formElement($submit);
    ?>
</div>
<?php
echo $this->form()->closeTag();
?>
<div class="bottom-link">
    <a href="<?php echo $this->url('home') ?>">Back to home</a>
    / 
    <a href="<?php echo $this->url('users/login') ?>">Back to login</a>
</div>