<?php
$title = 'Reset Your Password';
?>

<h2 class="form-small-heading"><?php echo $this->escapeHtml($title); ?></h2>
<?php echo $this->partial('zf2auth/elements/message.phtml', array('flashMessages' => $this->flashMessages, 'error' => $this->error)); ?>
<?php
$successMessage = "";
foreach ($this->flashMessages as $mess) {
    $successMessage = $mess["success"];
}
if (empty($successMessage) && is_object($this->form)) {

    $form = $this->form;
    $form->setAttribute('action', $this->url('users/reset-password', array('id' => $id, 'password_access_tocken' => $password_access_tocken)));
    $form->setAttribute('id', 'resetPasswordForm');
    $form->prepare();
    echo $this->form()->openTag($form);
    $allname = array();
    foreach ($form as $element) :
        $name = $element->getAttribute('id');
        $allname[] = $name;
        $$name = $element;
    endforeach;


    foreach ($form as $element) :

        echo $this->formElement($element);
        if ($this->formElementErrors($element)):
            ?>
            <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
            <?php
        endif;

    endforeach;
}else {
    ?>
    To log in, <a href="<?php echo $this->url('users/login'); ?>">Click Here</a>
    <?php
}
?>
