<?php
if (!empty($getIdentity)) {
    $nameString = $userData->name;
    $nameString = (strlen($nameString) > 15) ? substr($nameString, 0, 12) . '...' : $nameString;
    ?>

    <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Hello, <?php echo $nameString; ?>! <span class="caret"></span></a>
            <ul role="menu" class="dropdown-menu">
                <li><a href="<?php echo $this->url('home'); ?>">My Account</a></li>
                <li><a href="<?php echo $this->url('users/change-password'); ?>">Change password</a></li>
                <li class="divider"></li>
                <li><a href="<?php echo $this->url('users/logout'); ?>">Logout</a></li>
            </ul>
        </li>
    </ul>
    <?php
} else {
    ?>
    <div class='header-form'>
        <div class="pull-right">
            <div class="btn-group dropup" style="margin-top: 10px;">
                <a type="button" class="btn btn-default" id="loginbtn" href="<?php echo $this->url('users/login'); ?>"><span class="glyphicon glyphicon-user"></span></a>
                <a type="button" class="btn btn-default" id="loginbtn" href="<?php echo $this->url('users/login'); ?>">User Log In</a>
            </div>
        </div>
    </div>
    <?php
}
?>


