<?php
$displayRange_array = array(
    'order_by' => $order_by,
    'order' => $order
);
if (!empty($search_by)) {
    $displayRange_array['search_by'] = $search_by;
}
?>
<a class="btn btn-default" data-toggle="dropdown" href="#">Display per page <?php echo $item_per_page; ?> <span class="caret"></span></a>
<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <?php
    $displayRanges = array(
        10, 25, 50, 100
    );
    foreach ($displayRanges as $displayRange) {
        $displayRange_array['item_per_page'] = $displayRange; // $displayRange_array comes from index page
        ?>
        <li><a
                href="<?php echo $this->url($pageAction, $displayRange_array); ?>"><?php echo $displayRange; ?></a></li>
            <?php
        }
        ?>
</ul>
