<?php
$first_array = array(
    'page' => $this->first,
    'order_by' => $order_by,
    'order' => $order,
    'item_per_page' => $item_per_page,
);
$prevous_array = array(
    'page' => $this->previous,
    'order_by' => $order_by,
    'order' => $order,
    'item_per_page' => $item_per_page,
);
$page_array = array(
    'order_by' => $order_by,
    'order' => $order,
    'item_per_page' => $item_per_page,
);
$next_array = array(
    'page' => $this->next,
    'order_by' => $order_by,
    'order' => $order,
    'item_per_page' => $item_per_page,
);
$last_array = array(
    'page' => $this->last,
    'order_by' => $order_by,
    'order' => $order,
    'item_per_page' => $item_per_page,
);

if (!empty($search_by)) {
    $first_array['search_by'] = $search_by;
    $prevous_array['search_by'] = $search_by;
    $page_array['search_by'] = $search_by;
    $next_array['search_by'] = $search_by;
    $last_array['search_by'] = $search_by;
}
?>

<?php if ($this->pageCount): ?>
    <div class="pagination-centered text-right">
        <ul class="pagination">
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction, $first_array); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction, $prevous_array); ?>">&lsaquo;</a></li>


            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php $page_array['page'] = $page; ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>>
                    <a href="<?php echo $this->url($pageAction, $page_array); ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction, $next_array); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url($pageAction, $last_array); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>