<?php
if ($section == 'head') {
    ?>
    <div class="panel">
        <div class="panel-heading" id="heading<?php echo $id; ?>">
            <h4 class="panel-title">
                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapse<?php echo $id; ?>">
                    <?php
                    echo $id . '. ';
                    $string = $name;
                    $patterns = array();
                    $patterns[0] = '/occ_/';
                    $patterns[1] = '/ast_/';

                    $replacements = array();

                    $replacements[1] = '';
                    $replacements[0] = '';
                    echo preg_replace($patterns, $replacements, $string);
                    ?>
                </a>
            </h4>
        </div>
        <div id="collapse<?php echo $id; ?>" class="panel-collapse collapse">
            <div class="panel-body">
                <table class="table table-hover general-table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <?php
                            foreach ($roles as $role) {
                                ?>
                                <th><?php echo $this->UtilHelper()->truncate($role->name, 5, ''); ?></th>
                                <?php
                            }
                            ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                    } else if ($section == 'tail') {
                        ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <?php
}
?>



